repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
          - id: check-executables-have-shebangs
          - id: check-merge-conflict
          - id: check-toml
          - id: end-of-file-fixer
          - id: mixed-line-ending
            args: [--fix=lf]
          - id: requirements-txt-fixer
          - id: trailing-whitespace
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.2.2
      hooks:
        - id: ruff
    - repo: https://github.com/psf/black
      rev: 24.2.0
      hooks:
          - id: black
    - repo: https://github.com/codespell-project/codespell
      rev: v2.2.6
      hooks:
      - id: codespell
        additional_dependencies:
          - tomli
